function txt = parse4datacursor(~,event_obj,data)

idx = get(event_obj, 'DataIndex');

try 
    flist=data.filelist{idx};
catch
    flist='no filename';
end
switch event_obj.Target.DisplayName
    case 'default'
        txt = {['x: ',num2str(data.i(idx))],...
               ['y: ',num2str(idx)]};
    case 'sample'
        txt = {['data.i: ',num2str(data.i(idx))],...
               ['index: ',num2str(idx)],...
               ['filename: ',flist],...
               ['y: ',num2str(event_obj.Target.YData(idx))]};
    case 'emission'
        txt = {['index: ',num2str(idx)],...
               ['em: ',num2str(data.Em(idx)),'nm'],...
               ['y: ',num2str(event_obj.Target.YData(idx))]};        
    case 'excitation'
        txt = {['index: ',num2str(idx)],...
               ['ex: ',num2str(data.Ex(idx)),'nm'],...
               ['y: ',num2str(event_obj.Target.YData(idx))]};     
    case 'contourf'
        posi = get(event_obj, 'Position');
        txt = {['ex: ',num2str(posi(1)),'nm'],...
               ['em: ',num2str(posi(2)),'nm'],...
               ['value: ',num2str(round(posi(3),3))]};     
    otherwise
        txt = {['x: ',num2str(event_obj.Target.XData(idx))],...
               ['y: ',num2str(event_obj.Target.YData(idx))]};
end
end
